### ISSUE TITLE
Monetization?

### ISSUE THREAD

**Issue by chao1995** [paradite/sg-tech-list#18]
In the intro, it says:
> The list is not meant to be exhaustive. I am not affiliated to any companies listed.

But you definitely know people who work in some of the companies listed, so somewhat "indirectly affiliated".

Since most tech companies hand out referral bonuses anyways, why do you do them such a favour by listing their names here, without, you know, making some money?

Possible turning this repo into a full-fledged web app that connect job applicants to insiders? I know, I know, headhunting is not new business, but it is definitely profitable.

**Comment by chao1995** [comment]
Oh btw, the slogan could be "built by retired software developers, for aspiring software developers". 😉

**Comment by paradite** [comment]
I have no plans to monetize this for now.
